const translations = {
    ar: {
        pageTitle: "سودارينت",
        changeLanguge: "Change Languge",
        title: "سودارينت",
        description: "منصة 'سودارينت' تمنحك تقديرًا منصفًا لسعر الإيجار استنادًا إلى مواصفات العقار وموقعه، ليساعدك على الوصول إلى سعر عادل ومناسب للطرفين بسهولة وسرعة.",
        nextBtn: "ابدأ الحساب",
        head1name: "المساحة والمرافق الخارجية",
        head2name: "مكونات العقار الداخلية",
        head3name: "الخدمات الأساسية",
        head4name: "مستوى النظافة",
        head5name: "الموقع",
        head6name: "الخدمات الاخرى",
        unit: "متر مربع",
        space: "مساحة العقار",
        balcony: "بلكونه؟",
        courtyard: "حوش (مساحة خارجية)؟",
        room: "الغرف",
        bathroom: "الحمامات",
        living: "عدد الصالات",
        ice: "المكيفات",
        water: "هل يوجد مياه؟",
        electricity: "هل يوجد كهرباء؟",
        option: "الخيارات",
        area: "المنطقة",
        district: "الحي",
        school: "مدارس قريبة",
        market: "أسواق أو مراكز",
        bas: "طريق مواصلات",
        sendData: "إحسب الأن",
        furnished: "مفروش؟",
        titleResult: "تقدير سعر الإيجار",
        sdg: "جنيه سوداني",
        alirtText: "يرجى تعبئة جميع الحقول المطلوبة قبل المتابعة",
        alirtBtn: "حسناً"
    },
    en: {
        pageTitle: "Sudarent",
        changeLanguge: "تغير اللغة",
        title: "Sudarent",
        description: "Sudarent gives a fair rental estimate based on property details and location, helping you agree on a price quickly.",
        nextBtn: "Start Calculation",
        head1name: "Area and outdoor facilities",
        head2name: "Internal property components",
        head3name: "Basic services",
        head4name: "Cleanliness level",
        head5name: "Location",
        head6name: "Other services",
        unit: "square meter",
        space: "property area",
        balcony: "balcony?",
        courtyard: "courtyard?",
        room: "Rooms",
        bathroom: "Bathrooms",
        living: "Number of living rooms",
        ice: "Air Conditioners",
        water: "Is there water?",
        electricity: "Is there electricity?",
        option: "Options",
        area: "Area",
        district: "District",
        school: "Nearby schools",
        market: "Markets or Mall",
        bas: "Transportation route",
        sendData: "Count Now",
        furnished: "Furnished?",
        titleResult: "Rental price estimate",
        sdg: "Sudanese Pound",
        alirtText: "Please fill in all required fields before proceeding",
        alirtBtn: "OK!",
    }
};
